openapi: 3.0.0
info:
  title: Sample User API
  version: 1.0.0
  description: API for managing users
  contact:
    name: API Support
    email: support@example.com

servers:
  - url: http://localhost:8080

paths:
  /users:
    post:
      summary: Create a new user
      description: This endpoint creates a user in the system.
      operationId: createUser
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':  # <-- updated from '200' to '201'
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'


components:
  schemas:
    User:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: John Doe
